version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
