version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: dad-jokes-postgres
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
